---
apiVersion: v1
kind: Secret
metadata:
  name: ml8s-postgres-superuser
  namespace: ml8s-dev-cnpg
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: ml8s-postgres-app-user
  namespace: ml8s-dev-cnpg
type: kubernetes.io/basic-auth
stringData:
  username: flyte
  password: flytepass
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ml8s-postgres
  namespace: ml8s-dev-cnpg
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1-system-trixie
  postgresql:
    parameters:
      shared_buffers: "256MB"
      max_connections: "100"
  superuserSecret:
    name: ml8s-postgres-superuser
  bootstrap:
    initdb:
      database: flyteadmin
      owner: flyte
      secret:
        name: ml8s-postgres-app-user
  storage:
    storageClass: "standard"
    size: 8Gi
